//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuotesWebApp.Models
{
    using System.Collections.Generic;

    public partial class AutoQuote
    {
        public AutoQuote()
        {

        }

        public AutoQuote(int id)
        {
            AutoQuoteId = id;
        }

        public int AutoQuoteId { get; set; }
        public System.DateTime QuoteGenerationDate { get; set; }
        public int InsureeId { get; set; }
        public decimal BaseRate { get; set; }
        public decimal AgeUnder18Rate { get; set; }
        public decimal AgeBtwn19and25Rate { get; set; }
        public decimal AgeOver25Rate { get; set; }
        public decimal AutoYearBefore2000Rate { get; set; }
        public decimal AutoYearBtwn2000and2015Rate { get; set; }
        public decimal AutoYearAfter2015Rate { get; set; }
        public decimal IsPorscheRate { get; set; }
        public decimal IsCarreraRate { get; set; }
        public decimal SpeedingTicketsRate { get; set; }
        public decimal SubtotalBeforeDuiCalc { get; set; }
        public decimal DuiRateUp25Percent { get; set; }
        public decimal SubtotalAfterDuiCalc { get; set; }
        public decimal CoverageTypeRateUp50Percent { get; set; }
        public decimal SubtotalAfterCoverageCalc { get; set; }
        public decimal MonthlyQuoteRate { get; set; }
        public decimal YearlyQuoteRate { get; set; }

        public virtual Insuree Insuree { get; set; }
        public virtual ICollection<AutoQuote> AutoQuotes { get; set; }
    }
}
