// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuotesWebApp.Models
{
    using AutoQuotesWebApp.ViewModels;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AutoQuote
    {
        public AutoQuote()
        {

        }

        public AutoQuote(int id)
        {
            AutoQuoteId = id;
        }

        public AutoQuote(QuoteItemizationVM quoteVM)
        {
            QuoteGenerationDate = quoteVM.QuoteGenerationDate;
            BaseRate = quoteVM.BaseRate;
            AgeUnder18Rate = quoteVM.AgeUnder18Rate;
            AgeBtwn19and25Rate = quoteVM.AgeBtwn19and25Rate;
            AgeOver25Rate = quoteVM.AgeOver25Rate;
            AutoYearBefore2000Rate = quoteVM.AutoYearBefore2000Rate;
            AutoYearBtwn2000and2015Rate = quoteVM.AutoYearBtwn2000and2015Rate;
            AutoYearAfter2015Rate = quoteVM.AutoYearAfter2015Rate;
            IsPorscheRate = quoteVM.IsPorscheRate;
            IsCarreraRate = quoteVM.IsCarreraRate;
            SpeedingTicketsRate = quoteVM.SpeedingTicketsRate;
            SubtotalBeforeDuiCalc = quoteVM.SubtotalBeforeDuiCalc;
            DuiRateUp25Percent = quoteVM.DuiRateUp25Percent;
            SubtotalAfterDuiCalc = quoteVM.SubtotalAfterDuiCalc;
            CoverageTypeRateUp50Percent = quoteVM.CoverageTypeRateUp50Percent;
            MonthlyQuoteRate = quoteVM.MonthlyQuoteRate;
            YearlyQuoteRate = quoteVM.YearlyQuoteRate;
        }

        public int AutoQuoteId { get; set; }
        [DataType(DataType.Date)]
        public DateTime QuoteGenerationDate { get; set; }
        public int InsureeId { get; set; }
        public decimal BaseRate { get; set; }
        public decimal AgeUnder18Rate { get; set; }
        public decimal AgeBtwn19and25Rate { get; set; }
        public decimal AgeOver25Rate { get; set; }
        public decimal AutoYearBefore2000Rate { get; set; }
        public decimal AutoYearBtwn2000and2015Rate { get; set; }
        public decimal AutoYearAfter2015Rate { get; set; }
        public decimal IsPorscheRate { get; set; }
        public decimal IsCarreraRate { get; set; }
        public decimal SpeedingTicketsRate { get; set; }
        public decimal SubtotalBeforeDuiCalc { get; set; }
        public decimal DuiRateUp25Percent { get; set; }
        public decimal SubtotalAfterDuiCalc { get; set; }
        public decimal CoverageTypeRateUp50Percent { get; set; }
        public decimal SubtotalAfterCoverageCalc { get; set; }
        public decimal MonthlyQuoteRate { get; set; }
        public decimal YearlyQuoteRate { get; set; }

        public virtual Insuree Insuree { get; set; }
        public virtual ICollection<AutoQuote> AutoQuotes { get; set; }
    }
}
