//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuotesWebApp.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Insuree
    {



        public int InsureeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Required(ErrorMessage = "Required Field. Enter Email Address.")]
        public string EmailAddress { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DateOfBirth { get; set; }
        public int AutoYear { get; set; }
        public string AutoMake { get; set; }
        public string AutoModel { get; set; }
        public int SpeedingTickets { get; set; }
        public bool DUI { get; set; }
        public bool CoverageType { get; set; }
        public Nullable<decimal> MonthlyRate { get; set; }
        public Nullable<decimal> YearlyRate { get; set; }

        public Insuree()
        { }

        public Insuree(InsureeVM insureeVm)
        {
            InsureeId = insureeVm.VmInsureeId;
            FirstName = insureeVm.VmFirstName;
            LastName = insureeVm.VmLastName;
            EmailAddress = insureeVm.VmEmailAddress;
            DateOfBirth = insureeVm.VmDateOfBirth;
            AutoYear = insureeVm.VmAutoYear;
            AutoMake = insureeVm.VmAutoMake;
            AutoModel = insureeVm.VmAutoModel;
            SpeedingTickets = insureeVm.VmSpeedingTickets;
            DUI = insureeVm.VmDUI;
            CoverageType = insureeVm.VmCoverageType;
            MonthlyRate = insureeVm.VmMonthlyRate;
            YearlyRate = insureeVm.VmYearlyRate;
        }

        public Insuree(int insureeId, string firstName, string lastName, string emailAddress,
                       DateTime dateOfBirth, int autoYear, string autoMake, string autoModel, int speedingTickets, bool dui, bool coverageType,
                       decimal monthlyRate, decimal yearlyRate)
        {

        }


    }
}
