//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuotesWebApp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Insuree
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insuree(Insuree id)
        {
            this.AutoQuotes = new HashSet<AutoQuote>();
        }

        public Insuree() { }

        public int InsureeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int AutoYear { get; set; }
        public string AutoMake { get; set; }
        public string AutoModel { get; set; }
        public int SpeedingTickets { get; set; }
        public bool DUI { get; set; }
        public bool CoverageType { get; set; }
        public Nullable<System.DateTime> DoNotEmail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoQuote> AutoQuotes { get; set; }
    }
}
